### ISSUE TITLE
Feature request: citation support

### ISSUE THREAD

**Issue by goxberry** [vmg/redcarpet#185]
One thing I've noticed is that GitHub-flavored Markdown does not have particularly good support for citations. If I want to cite something in my README file, or on my GitHub Pages, I'd need to do so manually, which can be error-prone, and hyperlinks aren't necessarily a good fallback, because the material I cite may not be online (or freely available online). Would it be possible to add a feature that enables auto-generation of citation of books, articles, and other materials? This feature could be useful for projects that are digital companions to written works, or for projects that have a print presence (academic and government projects come to mind, but perhaps there are others?).

**Comment by robin850** [comment]
Hi there !

Sorry for the late answer but I will give it a close. Actually Markdown isn't intended to write papers or books in general. Supporting CSL for instance would be pretty costly and would only be used by a few people because Redcarpet is mainly used for documentation or blogging. You can always implement a custom render object, extending `Redcarpet::Render::HTML` and redefining the `block_quote` callback.

Thanks anyway for the proposal, we appreciate it !
