### ISSUE TITLE
Duplicate anchor names

### ISSUE THREAD

**Issue by Tuckie** [vmg/redcarpet#307]
When you have a headers with the same names, duplicate anchors are created.

```
# a section
## a subsection
# another section
## a subsection
# another section
```
# 

```
id="a-section"
id="a-subsection"
id="another-section"
id="a-subsection"
id="another-section"
```

One fix would be to append -2, -3, -4... when an anchor with the same name as a prior anchor is found.

```
id="a-section"
id="a-subsection"
id="another-section"
id="a-subsection-2"
id="another-section-2"
```

Another interesting option (that wouldn't cut down on all collisions, so the first idea would have to be a fallback) would be to always prepend the section it is located in.

```
id="a-section"
id="a-section--a-subsection"
id="another-section"
id="another-section--a-subsection"
id="another-section-2"
```

**Comment by HugoGiraudel** [comment]
Is there any ETA on this?

**Comment by giuseppeg** [comment]
bump?

**Comment by robin850** [comment]
Hi there,

Sorry but actually I think that this is not something that should handled at our level since people may want to handle duplicates very differently and I don't want to provide an option for every single case and since it may take some time to be implemented in C, here are two custom render to handle duplicates easily:

~~~ruby
# The "numeric" way; if you have the same title twice
# then a number is appended to the anchor.
class NumericRender < Redcarpet::Render::HTML
  def initialize(opts = {})
    super
    @anchors = []
  end

  def header(text, level)
    number = 2
    anchor = text.downcase.gsub(' ', '-')

    while @anchors.include?(anchor)
      if number > 2
        anchor[-1] = number.to_s
      else
        anchor += "-#{number}"
      end

      number += 1
    end

    @anchors << anchor

    %(<h#{level} id="#{anchor}">#{text}</h#{level}>)
  end
end

# The "Back-tracking" way; if you have the same title
# twice, it will concatenate its anchor with the
# upper title's one.
class BackTrackRender < Redcarpet::Render::HTML
  Anchor = Struct.new(:value, :level)

  def initialize(opts = {})
    super
    @anchors = []
  end

  def header(text, level)
    anchor = Anchor.new(text.downcase.gsub(' ', '-'), level)

    if @anchors.any? {|a| a.value == anchor.value}
      parent = @anchors.reverse.find {|a| a.level < level }
      anchor.value = [parent.value, anchor.value].join('-')
    end

    @anchors << anchor

    %(<h#{level} id="#{anchor.value}">#{text}</h#{level}>)
  end
end
~~~

I'm giving this a close. Sorry for letting this open for such a long a time and finally closing it with a comment that is mostly "Deal with it" but the maintenance cost isn't worth the result. Thank you very much anyway ! :-)

**Comment by toolness** [comment]
Thanks for the workarounds! Totally understandable that the maintenance cost isn't worth the result here.

That said, I wanted to mention two things I noticed:

* The code used to generate a custom `id` in the workarounds, `text.downcase.gsub(' ', '-')`, is a bit different from that used in the [`rndr_header_anchor()`](https://github.com/vmg/redcarpet/blob/26c80f05e774b31cd01255b0fa62e883ac185bf3/ext/redcarpet/html.c#L273-L319) function in the C implementation. A closer approximation to it might be:

    ```ruby
    text.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
    ```

    This is recommended by https://stackoverflow.com/a/4308399.

* While it might be obvious to some, another alternative workaround that doesn't require writing any ruby is to simply to write raw HTML instead of markdown for headers that have conflicting ids, e.g. `<h2>a subsection</h2>` instead of `## a subsection`, or even `<h2 id="my-custom-id">a subsection</h2>` if you want to provide a custom id. Obviously this isn't great for readability, but it's a decent solution if you either don't want to, or are unable to, resort to writing ruby.
