### ISSUE TITLE
Add math blocks that render with MathJax

### ISSUE THREAD

**Issue by hickford** [vmg/redcarpet#313]
Pandoc and Kramdown support Tex/Latex math blocks that render using Mathjax. It would be nice if Redcarpet did too.

See the Kramdown documentation http://kramdown.rubyforge.org/syntax.html#math-blocks for the syntax and an example.  See also the Pandoc documentation http://johnmacfarlane.net/pandoc/README.html#math

**Comment by TruePath** [comment]
To be clear all that's needed to properly support latex using MathJax is for the parser to recognize $ delimited spans and $$ delimited blocks (and maybe \( \) and \[ \] delimiters too as aliases for $ and $$ respectively) and leave them alone.  MathJax itself is happy to do all the heavy lifting to render and parse the latex the problem is just that latex math uses symbols that redcarpet will think are markdown elements and mess it up.

If this doesn't already exist it shouldn't be too hard to add.  When I get to the point where I start running into this problem in my project I'll see if I can put together a pull request to do it but I felt I should mention right now that it doesn't require mucking about with parsing latex or anything but passing through certain delimited regions unaltered.  So it doesn't add a new heavyduty feature and it's a common use case.
