### ISSUE TITLE
CommonMark conformance

### ISSUE THREAD

**Issue by Envek** [vmg/redcarpet#429]
What do project maintainers think about [CommonMark](http://commonmark.org/) initiative to create full and unambigous specification for basic Markdown (without extensions). Is (or will be) it planned for a some point of time?

The current specification is there: http://spec.commonmark.org/
Repository with reference implementation and conformance tests is there: https://github.com/jgm/CommonMark

Conformance to CommonMark will fix bugs such as #230 and will help to avoid them in future. And, that is more important, will reduce the inconsistencies between implementations.

Result of Redcarpet 3.2.0 (command line utility) on CommonMark 0.6 conformance tests is: `213 tests passed, 256 failed, 0 skipped.`

The testing was done like so:

``` bash
git clone https://github.com/jgm/CommonMark.git
cd CommonMark
# install re2c like: brew install re2c
make
make test # Testing of reference implementation: 469 tests passed, 0 failed, 0 skipped.
gem install redcarpet
PROG=redcarpet make test # 213 tests passed, 256 failed, 0 skipped.
```

**Comment by Ajedi32** [comment]
So apparently Sundown [is deprecated](https://github.com/vmg/sundown/blob/master/CONTRIBUTING.md) now in favor of CommonMark? The CommonMark reference implementation is [here](https://github.com/jgm/cmark), but presumably there will be other parsers which conform to the standard.

**Comment by waldyrious** [comment]
> presumably there will be other parsers which conform to the standard.

[There are.](https://github.com/jgm/CommonMark/wiki/List-of-CommonMark-Implementations)

**Comment by MrPetovan** [comment]
Hi, I'm interested in CommonMark conformance to maximize compatibility between http://github.com/diaspora/diaspora (using RedCarpet) and http://github.com/friendica/friendica (written in PHP). Is it still in the works?

**Comment by noraj1337** [comment]
another related issue https://github.com/github/markup/issues/1014

**Comment by kivikakk** [comment]
RedCarpet won't be supporting CommonMark any time soon. Consider using [`commonmarker`](https://github.com/gjtorikian/commonmarker), which is what GitHub now uses to render Markdown everywhere.

**Comment by robin850** [comment]
Hi there,

Sorry, I've never commented here but here are some thoughts about this:

* Conforming to CommonMark would sure fix a bunch of bugs that have been there forever and improve the match between how Redcarpet behaves and how people expect it to behave.
* If Redcarpet supports CommonMark, it would be in version 4.0 since we would introduce breaking changes (e.g. translating tabs to spaces wouldn't be done anymore). The main problem with this is that the 3.x series should certainly still be supported for fixing eventual security issues ; some people may still want the original Markdown or may not be able to upgrade easily given that they've written a lot of documents conforming with the "buggy" behaviors of Redcarpet.
* Some people use this library over other Markdown parsers because of the speed and the easy API. CommonMarker doesn't provide as much options as Redcapet does but provides a similar API for render object. Though, it's not quite the same and I'm not a huge fan of it. However, maybe that something that can be improved !
* I haven't used CommonMarker in any production project but since, as far as I remember, CommonMark generates an AST before generating the final output, it should be slower and more memory consuming than Redcarpet. If CommonMarker is used by GitHub, it's certainly battle-tested and pretty efficient but maybe Redcarpet is still a better fit for tinier projects. Just thinking out loud here, I'm maybe totally wrong as I didn't benchmark anything !

A general message about the project for people skimming this thread: I'm sorry Redcarpet isn't really active anymore but my resources are pretty limited since I'm committed to other open source projects and still a student. Feel free to use any existing alternative ; this project isn't the great tool it used to be when it was maintained by Vicent.

**Comment by robin850** [comment]
Hello there,

Just commenting to say that Redcarpet will not conform to CommonMark in the near future. That would require a lot of work and would be counter productive as there already are alternatives like CommonMarker. This library will still be maintained for people using "plain old" Markdown. 

I'm giving this a close ; thanks !
