### ISSUE TITLE
Lists rendered incorrectly

### ISSUE THREAD

**Issue by maclover7** [vmg/redcarpet#512]
For some reason, redcarpet is not rendering lists correctly, when there is a new line in between list items. Instead of going 1, 2, etc., redcarpet displays the list as 1, 1, etc.

Is there anyway to fix this without having to remove the lines between list items?

**Please note that Github displays the markdown correctly (without the bug I am seeing).**

---

**Context / Important Stuff:**

*Parsing Strategy:*
```ruby
redcarpet = Redcarpet::Markdown.new(CustomHtml.new(hard_wrap: true), tables: true, no_intra_emphasis: true, fenced_code_blocks: true, lax_spacing: true)
```
and
```ruby
rendered_markdown = redcarpet.render(markdown)
```

*Markdown to be Parsed:*
```
1. blahblah

* blah

2. blahblah
```

**Comment by robin850** [comment]
Hi  @maclover7,

Actually I guess this is the expected output ; you've three different lists. The fact that beginning a line with `2.` produces a new list is because people can actually use any number to generate an ordered list like:

~~~
1. One
1. Two
1. Three
~~~

By the way, CommonMark produces the same output as Redcarpet with such Markdown.

I'm giving it a close but thanks for reporting anyway!
