### ISSUE TITLE
tables: all rows that are longer than the thead row are truncated

### ISSUE THREAD

**Issue by slang800** [vmg/redcarpet#555]
Given this markdown (as `test.md`):

```markdown
0,0 | 0,1 | 0,2 |
--- | --- | --- | ---
1,0 | 1,1 | 1,2 | 1,3
2,0 | 2,1 | 2,2 | 2,3
```

Running `redcarpet --parse-tables < test.md` results in the following output:

```html
<table><thead>
<tr>
<th>0,0</th>
<th>0,1</th>
<th>0,2</th>
</tr>
</thead><tbody>
<tr>
<td>1,0</td>
<td>1,1</td>
<td>1,2</td>
</tr>
<tr>
<td>2,0</td>
<td>2,1</td>
<td>2,2</td>
</tr>
</tbody></table>
```

As you can see above, cells `1,3` and `2,3` are missing from the output, and I think that's a bug. This behavior hides content that could be important to readers, without so much as a parser error. And that can be a pain when you're not carefully checking what your markdown looks like after compilation. For example, an extra cell jutting out of an otherwise rectangular table, or a missing header is an easy error to spot, while a column missing still leaves the table looking correct and orderly.

Even if you are looking at the output in a graphical/rendered form while you're editing, it's annoying to start a table cell in a new column and not be able to see what you are typing until you add a header for that column.

**Comment by robin850** [comment]
Hi @slang800,

Actually Redcarpet infers the number of columns of your table based on the number of columns that there's inside your table header. Since it is looking for an alpha-numeric char when there's no end separator, the last column isn't considered as one. To fix this problem, you can simply write your Markdown as follow:

~~~markdown
0,0 | 0,1 | 0,2 |     |
--- | --- | --- | --- |
1,0 | 1,1 | 1,2 | 1,3 |
2,0 | 2,1 | 2,2 | 2,3 |
~~~

I'm giving this a close, thanks for spotting this anyway and sorry for the late answer ! :-)
