### ISSUE TITLE
`content` argument of `footnote_def` has `<p>` tags around it

### ISSUE THREAD

**Issue by DZittersteyn** [vmg/redcarpet#562]
I am trying to customize the rendering of footnotes, and I ran into the following issue:

I created a custom renderer which overrides the relevant block- and span-level calls:
```
class FootnoteMWE < Redcarpet::Render::HTML

  def footnotes(content)
    "|#{content}|"
  end

  def footnote_def(content, number)
    "{#{content}}"
  end

  def footnote_ref(number)
    "(#{number})"
  end

end
```

and called it with `Redcarpet::Markdown.new(FootnoteMWE, {footnotes: true}).render "test[^1] \n [^1]: foo"`.

I expected this to result in the following output:
```
<p>test(1) </p>
|{foo}|
```

The result however is:
```
<p>test(1) </p>
|{<p>foo</p>
}|
```
`<p>` tags were introduced around the `footnote_def` `content`.

With the unmodified HTML renderer, and the same input:
`Redcarpet::Markdown.new(Redcarpet::Render::HTML, {footnotes: true}).render "test[^1] \n [^1]: foo"`
I get 

```
<p>test<sup id="fnref1"><a href="#fn1" rel="footnote">1</a></sup> </p>

<div class="footnotes">
<hr>
<ol>

<li id="fn1">
<p>foo&nbsp;<a href="#fnref1" rev="footnote">&#8617;</a></p>
</li>

</ol>
</div>
```
Which does not have these tags around "foo", which leads me to wonder if there is something I'm not overriding that I should be.

Is there any way I can get rid of the `<p>` tags that are present in the `content` argument without editing `content`, or is it impossible to generate the markdown that Render::HTML generates that way?

**Comment by robin850** [comment]
Hi @DZittersteyn,

Nope, this is not possible without removing the `<p>` tag from the given content; actually the given output seems sometimes weird when you are overriding the default callbacks but you would actually expect emphasis or code-spans to be parsed inside your footnote definition if you would use such elements.

You can use `content[3..-5]` instead of just `content` inside your method.

I'm giving this a close, thanks for spotting that anyway ! :-)
