### ISSUE TITLE
Implementing transclusion

### ISSUE THREAD

**Issue by mariusor** [vmg/redcarpet#586]
Hi, I am working on a project which needs a form of file transclusion[1] implemented. 

In short, the syntax I wanted to add to the parser would be similar to inline links: ```:[name](path/to/markdown.md)``` - thre's an extra colon in first position -  inspired by one of the comments in the commonmark discussion [2]. 

I want to add this feature but I couldn't find any obvious way of injecting my logic into the parser - especially since there's a specific comment regarding monkey patching. Is there something I'm missing, or am I approaching the problem the wrong way?

[1] https://talk.commonmark.org/t/transclusion-or-including-sub-documents-for-reuse/270
[2] https://talk.commonmark.org/t/transclusion-or-including-sub-documents-for-reuse/270/7

**Comment by robin850** [comment]
Hi @mariusor,

It is actually possible to create a custom render object like this:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def preprocess(document)
    document.split("\n").map do |line|
      if line =~ /\:\[(.+)\]\((.+)\)/
        # Not sure what you want to do with the title
        # but you can reference it through `$1` here.
        File.read($2)
      else
        line
      end
    end.join("\n")
  end
end
~~~

> ... since there's a specific comment regarding monkey patching

I guess you are referring to this specific section of the README:

> On a related topic: if your Markdown gem has a `lib/markdown.rb` file that monkeypatches the Markdown class, you're a terrible human being. Just saying.

But that's another topic ; actually, most Markdown processors implement a `Markdown.new(text).to_html` API but the problem is that it is bad because you don't know which Markdown processor you are using since `Markdown` is a generic name so monkey-patching such class can be dangerous if you change your parser.

Anyway, Redcarpet provides a completely different API, the `#to_html` one is just kept to ease the transition from another parser and for the sake of backward compatibility.

I'm giving this a close but if you have any further question, feel free to ask ! :-)

**Comment by mariusor** [comment]
OK, thank you, @robin850.

This solves the issue, but then it seems to muddle the sepparation between parser and the renderer. Also it doesn't allow reusing (or extending) the logic for the link parsing itself.

**Comment by robin850** [comment]
> Also it doesn't allow reusing (or extending) the logic for the link parsing itself.

I'm not sure to understand what you mean here, could you explain please ?

**Comment by mariusor** [comment]
Well, I'm not sure how it would work for redcarpet, but usually one would be able to reuse the parts which parse the link elements, either by reusing the regular expression for links, or the parse method itself.

**Comment by robin850** [comment]
You can create a custom render object that extends from `Redcarpet::Render::HTML` and define a `link` method on it that will handle links as you wish.
