### ISSUE TITLE
Be able to differentiate between inline and block code blocks

### ISSUE THREAD

**Issue by leggsimon** [vmg/redcarpet#597]
Given this markdown

```markdown
Now tell `rvm` to use the new default by running
`` `
rvm --default use 2.3.3
`` `
```
 This will generate the html
```html
<p>Now tell <code>rvm</code> to use the new default by running</p>
<p>
  <code>rvm --default use 2.3.3</code>
</p>
```

Now in order to style these differently I can't differentiate what is inline code or a block of code.
It would be good to be able to add a class to be able to select them differently e.g.
```markdown
`rvm`
```
becomes
```html
<code class="inline-code">rvm</code>
```

and

```markdown
`` `
rvm --default use 2.3.3
`` `
```
becomes
```html
<p>
  <code class="block-code">rvm --default use 2.3.3</code>
</p>
```

**Comment by robin850** [comment]
Hi @leggsimon,

Actually you shouldn't put spaces after the second back-tick, otherwise Redcarpet doesn't consider it as a block code. Also, there should be an empty line between your paragraph and the block. You should rather write something like:

~~~markdown
Now tell `rvm` to use the new default by running

```
rvm --default use 2.3.3
```
~~~

And it will properly generate a `<code>` element wrapped inside a `<pre>` one. Also, make sure that the `:fenced_code_blocks` option is enabled instantiating the `Redcarpet::Markdown` object.

Finally, if you really want to customize the output to put the CSS classes that you asked for, you can implement a custom render object such as:

~~~ruby
class CustomRender < Redcarpet::Render::HTML
  def block_code(code, lang)
    %(<pre><code class="block-code">#{code}</code></pre>)
  end

  def codespan(code)
    %(<code class="inline-code">#{code}</code>)
  end
end
~~~

And use it instead of `Redcarpet::Render::HTML` instantiating `Redcarpet::Markdown`.

I'm giving this a close but thanks for spotting this ! :-)

**Comment by leggsimon** [comment]
Apologies, I only put in the space after the second backtick because I couldn't work out how to escape it in the issue and so Was going to look like this...

Now tell `rvm` to use the new default by running
```
rvm --default use 2.3.3
```
