### ISSUE TITLE
Duplicated ID generated from headers containing non-ASCII

### ISSUE THREAD

**Issue by ryym** [vmg/redcarpet#618]
Hi,

Currently, redcarpet properly converts a non-ASCII header to a hash string (#538). However, when a header contains ASCII and non-ASCII characters, redcarpet simply strips non-ASCII characters. This behavior can create a same ID from different header strings. For example:

```rb
require 'redcarpet'

renderer = Redcarpet::Render::HTML.new(with_toc_data: true)
markdown = Redcarpet::Markdown.new(renderer)

input = <<~MD
  ## Fooの始め方
  ## Fooのインストール
MD

puts markdown.render(input)
# =>
# <h2 id="foo">Fooの始め方</h2>
# 
# <h2 id="foo">Fooのインストール</h2>
```

This is a problem especially when I create a TOC. When I render a TOC from the above `input` text, `HTML_TOC` generates anchors for `Fooの始め方` and `Fooのインストール`, but both anchors have a same `href` which links to `#foo`.

Is there a way to avoid this ID duplication?

---

- ruby: 2.3.1-p112
- redcarpet: 3.4.0

**Comment by robin850** [comment]
Hello @ryym,

Actually no, there isn't any built-in feature to avoid duplicates. Unfortunately, this is intended as I don't want the anchor generation to be too complex and have a dozen different options because people want to handle duplicates in different ways (e.g. by adding the upper title anchor, by adding a number at the end of the anchor, etc.)

Thus, your best option is to implement a custom render to handle duplicates. There are examples [here](https://github.com/vmg/redcarpet/issues/307#issuecomment-261793668). Feel free to ask if something isn't clear.

I'm giving this a close but thanks for reporting this anyway ! :-)

**Comment by ryym** [comment]
OK, I understand. thank you for your explanation! :)
