### ISSUE TITLE
Question about syntax highlighting with fenced code blocks

### ISSUE THREAD

**Issue by ajwann** [vmg/redcarpet#622]
I'm using redcarpted with the HTML renderer and ```:highlight => true``` is turned on.

When I create a code block like so:
\```ruby
    class Foo
    end
\```
I don't see any syntax higlighting. I do however see in my browser that the code block was given ```class="ruby"```.

Should I be expecting to see syntax highlighting? Or does redcarpet just assign a class equal to whatever language I specified, leaving me to style the class myself?

**Comment by robin850** [comment]
Hello @ajwann,

Actually, the `:highlight` option allows you to write `==something==` and get `<mark>something</mark>` once it's parsed.

Redcarpet doesn't come with syntax highlighting out of the box because people have different needs or sometimes don't need it at all. You can easily highlight code with [Rouge](https://github.com/jneen/rouge). Once it's installed, you can do something like:

~~~ruby
require 'redcarpet'
require 'rouge'
require 'rouge/plugins/redcarpet'

class CustomRender < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end

parser = Redcarpet::Markdown.new(CustomRender, fenced_code_blocks: true)
parser.render("Your Markdown ...")
~~~

And then include a style-sheet provided by Rouge to properly show syntax highlighting on your page.

I hope this answers your question, feel free to ask if something isn't clear ! :-)
