### ISSUE TITLE
Redcarpet::Render::Base.block_quote reads nil as its parameter

### ISSUE THREAD

**Issue by hantuzun** [vmg/redcarpet#690]
I'm trying to only render a blockquote of a markdown in HTML.

Here's my subclass:
```rb
  class ArticleCardHTMLRender < Redcarpet::Render::Base
    def postprocess(full_document)
      """
      <div class='col-md-12'>
        #{full_document}
      </div>
      """.html_safe
    end

    def block_quote(quote)
      puts "quote"
      puts quote
      puts "quote"
      """
      <blockquote class='blockquote'>
        #{quote}
        placeholder
      </blockquote>
      """
    end
  end
```

When it renders, `quote` is not printed to the console.

When I replace `Redcarpet::Render::Base` with `Redcarpet::Render::HTML`, I get the expected output and see the following output in the console:

```
quote
<p>Example quote.</p>
quote
```

The issue doesn't happen with `header(text, header_level)`.

I use the latest version: 3.5.0.

**Comment by robin850** [comment]
Hello,

Sorry for the late answer but actually the problem lies in the fact that `Redcarpet::Render::Base` doesn't implement any method by default ; `nil` is returned from every callback so you have to provide an implementation for each of them.

Thus, to fix your problem, you might have to do the following:

~~~ruby
class ArticleCardHTMLRender < Redcarpet::Render::Base
  def paragraph(text)
    %(<p>#{text}</p>)
  end

  # ...
end
~~~

Or extends from `Redcarpet::Render::HTML` as you mentioned (it's generally easier to go this way).
