### ISSUE TITLE
Redcarpet::Render::StripDown don't remove syntax highlighting for fenced code blocks

### ISSUE THREAD

**Issue by elalemanyo** [vmg/redcarpet#722]
Hi,
Not really sure if this is a bug or a feature, but `Redcarpet::Render::StripDown` don't remove syntax highlighting for fenced code blocks. For example:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/3856862/159258999-3a83e287-fbc5-48d1-8640-ac2efeba1c55.png">

Can anyone tell me if this is expected?

**Comment by robin850** [comment]
Hello,

Actually this is because you didn't enable the `fenced_code_blocks` flag on `Redcarpet::Markdown`, thus, your fenced code block is actually parsed as a span code :

~~~ruby
markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown, fenced_code_blocks: true)

markdown.render <<-MD
```javascript
console.log("Hello");
```
MD
~~~

Thanks for reporting anyway!
