### ISSUE TITLE
:auto_link => target=_blank

### ISSUE THREAD

**Issue by HendrikRoth** [vmg/redcarpet#85]
Is there a nice way to display all links in new windows?

**Comment by bogdanr** [comment]
How would this work with github pages?

**Comment by robin850** [comment]
@bogdanr : This is not possible on GitHub, there's no way to achieve that through Markdown and the `target` attribute will be stripped out from any `a` element. By the way, GitHub isn't relying anymore on Redcarpet to process Markdown documents.

**Comment by lucascaton** [comment]
Easier/clener way:

```ruby
extensions = { fenced_code_blocks: true, strikethrough: true, tables: true, autolink: true }
renderer = Redcarpet::Render::HTML.new(hard_wrap: true, link_attributes: { target: '_blank' })
Redcarpet::Markdown.new(renderer, extensions).render('your markup here')
```

**Comment by mig-hub** [comment]
I much prefer all solutions using `link_attributes: { target: "_blank" }` especially @lucascaton 's one, but the problem is that it puts it on email links as well, which opens an empty page/tab on email links. Is there an option to avoid this while keeping a target blank on all other links? or creating a subclass is the only solution in this case?

I may be wrong but I don't see any reason to have target blank on email links.

**Comment by whurd-redcanary** [comment]
Note `link_attributes` is not available on `Redcarpet::Markdown.new`

**Comment by whurd-redcanary** [comment]
Also, TIL apparently best practice with `target: "_blank"` is to also use the HTML element `rel="noopener"`, for security reasons 
https://love2dev.com/blog/rel-noopener/

**Comment by lfigueras** [comment]
How to add target blank since  target "_blank" now uses noopener by default
